# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch:
        applies-to: 'version-updates'
        update-types:
          - 'minor'
          - 'patch'
      nuxt:
        patterns:
          - '*nuxt*'
      vue:
        patterns:
          - '*vue*'
          - '@vueuse*'
          - '*pinia*'
      ui:
        patterns:
          - '*ui*'
          - 'tailwind*'
          - '@tailwind*'
      db:
        patterns:
          - '*drizzle*'
      tooling:
        patterns:
          - '*eslint*'
          - '*stylelint*'
          - '*prettier*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: weekly

  # Enable version updates for Docker
  # - package-ecosystem: "docker"
  #   Look for a `Dockerfile` in the `root` directory
  #     directory: "/"
  #   Check for updates once a week
  #   schedule:
  #     interval: "weekly"
